name: publish_user_code_image
on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'
jobs:
  publish-user-code-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the user_code Docker image
      run: |
          docker build . --file Dockerfile_user_code --tag ghcr.io/user_code/user_code:$(date +%s)
          docker push ghcr.io/user_code/user_code:$(date +%s)