name: publish_dagster_image
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile_dagster'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile_dagster'
env:
  REGISTRY: ghcr.io
jobs:
  publish-dagster-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: name/app
        tags: |
          type=raw,value={{date 'YYYYMMDDHHMMSS'}}
    - name: Build the dagster Docker image
      run: |
          docker build . --file Dockerfile_dagster --tag ${{ env.REGISTRY }}/dagster/dagster:${{ DOCKER_METADATA_OUTPUT_VERSION }}
          docker push ${{ env.REGISTRY }}/dagster/dagster:${{ DOCKER_METADATA_OUTPUT_VERSION }}